name: Cron check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *' 

jobs:
  cron_check:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls    